config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'landing#index'

  # Create fancy login, logout and signup URLS.
  delete 'login', to: 'user_sessions#destroy', as: :destroy_session
  resources :users, only: %i[new create], path: 'signup', path_names: { new: '' }
  resources :user_sessions, only: %i[new create], path: 'login', path_names: { new: '' }


  namespace :dashboard, path: 'app' do
    root to: 'presentations#index'

    resources :previews, only: :show
    resources :presentations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/presentation.rb
# frozen_string_literal: true

class Presentation < ApplicationRecord
  belongs_to :user

  has_many :slides, -> { order(position: :asc) }, dependent: :destroy

  has_rich_text :description

  has_one_attached :source_file

  validates :name, presence: true
  validates :source_file, attached: true, content_type: :pdf

  after_commit :schedule_slides_extraction

  # TODO: https://github.com/diegotoral/pressy/issues/31
  def cover
   slides.first.try(:background_image)
  end

  def add_slide_from_io(io, filename, position)
    slide = slides.create!(position: position)
    slide.background_image.attach(io: io, filename: filename)
  end

  private

  def schedule_slides_extraction
    ExtractPresentationPagesJob.perform_later self
  end
end

app/models/slide.rb
# frozen_string_literal: true

class Slide < ApplicationRecord
  belongs_to :presentation

  acts_as_list scope: :presentation

  has_one_attached :background_image
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_authentic

  has_many :presentations, dependent: :delete_all

  validates :email,
    format: {
      with: /@/
    },
    length: { maximum: 100 },
    uniqueness: {
      case_sensitive: false,
      if: :will_save_change_to_email?
    }

  validates :password,
    confirmation: { if: :require_password? },
    length: {
      minimum: 8,
      if: :require_password?
    }

  validates :password_confirmation,
    length: {
      minimum: 8,
      if: :require_password?
    }

  def new_presentation(params = {})
    presentations.build(params)
  end
end

app/models/user_session.rb
# frozen_string_literal: true

class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend

  helper_method :current_user_session, :current_user

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)

    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)

    @current_user = current_user_session&.user
  end

  protected

  def paginate(collection)
    @pagy, collection = pagy(collection)
    collection
  end

  def authenticate_user!
    return if current_user

    flash[:alert] = t('authentication.not_authorized')
    redirect_to new_user_session_path
  end

  def handle_unverified_request
    current_user_session&.destroy
    redirect_to root_url
  end
end

app/controllers/dashboard/presentations_controller.rb
# frozen_string_literal: true

class Dashboard::PresentationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_presentation, except: %i[index new create]

  def index
    @presentations = paginate(current_user.presentations.order(created_at: :desc))
  end

  def new
    @presentation = current_user.new_presentation
  end

  def create
    @presentation = current_user.new_presentation presentation_params

    if @presentation.save
      flash[:success] = t('.success')
      ExtractPresentationPagesJob.perform_later @presentation

      redirect_to dashboard_presentations_path
    else
      flash[:error] = t('.error')

      redirect_to action: :new
    end
  end

  def edit
    @slides = @presentation.slides
      .map(&:background_image)
      .map { |image| url_for image.variant(resize_to_fit: [480, 320]) }
  end

  def update
    if @presentation.update_attributes presentation_params
      flash[:success] = t('.success')

      redirect_to dashboard_presentations_path
    else
      flash[:error] = t('.error')

      render :edit, layout: false, status: :unprocessable_entity
    end
  end

  def destroy
    @presentation.destroy
    flash[:success] = t('.success')

    redirect_to dashboard_presentations_path
  end

  private

  def set_presentation
    @presentation ||= current_user.presentations.find params[:id]
  end

  def presentation_params
    params
      .require(:presentation)
      .permit(:name, :description, :source_file)
  end
end

app/controllers/dashboard/previews_controller.rb
# frozen_string_literal: true

class Dashboard::PreviewsController < ApplicationController
  before_action :authenticate_user!

  def show
    @presentation = current_user.presentations.find params[:id]
  end
end

app/controllers/landing_controller.rb
# frozen_string_literal: true

class LandingController < ApplicationController
  layout 'landing'

  def index
  end
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

class UserSessionsController < LandingController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new user_session_params

    if @user_session.save
      flash[:success] = t('.success')

      redirect_to dashboard_root_url
    else
      flash[:error] = t('.error')

      render :new
    end
  end

  def destroy
    current_user_session.destroy

    redirect_to root_url
  end

  private

  def user_session_params
    params
      .require(:user_session)
      .permit(:email, :password, :password_confirmation)
      .to_h
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < LandingController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      flash[:success] = t('.success')

      redirect_to dashboard_root_path
    else
      flash[:error] = t('.error')

      render :new
    end
  end

  private

  def user_params
    params
      .require(:user)
      .permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

module NotificationsHelper
  # Wraps a flash in a `Notification` object which handles mapping flash keys to
  # the correct CSS class.
  Notification = Struct.new(:key, :message) do
    FLASH_TO_CSS_MAP = {
      alert: 'is-warning',
      error: 'is-danger',
      notice: 'is-info',
      success: 'is-success'
    }

    def css_class
      FLASH_TO_CSS_MAP[key.to_sym]
    end
  end

  def notifications
    flash.map { |key, value| Notification.new key, value }
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/application/_navigation.html.erb
<% content_for :navigation_end do %>
  <div class="navbar-item has-dropdown is-hoverable">
    <p class="navbar-item">
      <%= current_user.email %>
    </p>

    <div class="navbar-dropdown is-right">
      <%= link_to destroy_session_url, class: 'navbar-item', method: :delete do %>
        Logout
      <% end %>
    </div>
  </div>
<% end %>

<%= render 'shared/navigation' %>

app/views/application/index.html.erb
app

app/views/dashboard/presentations/_form.html.erb
<section class="section">
  <div class="field">
    <%= f.label :name, class: 'label' %>
    <div class="control">
      <%= f.text_field :name, class: 'input' %>
    </div>
    <% if f.object.errors[:name].any? %>
      <p class="help is-danger"><%= f.object.errors.full_messages_for(:name).first %></p>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :description, class: 'label' %>
    <div class="control is-fullheight">
      <%= f.rich_text_area :description, class: 'editor' %>
    </div>
  </div>
</section>

app/views/dashboard/presentations/_presentation.html.erb
<div class="column is-3">
  <div class="card" id="presentation-<%= presentation.id %>">
    <div class="card-image">
      <figure class="image is-4by3">
        <% if presentation.cover %>
          <%= image_tag presentation.cover.variant(resize_to_fit: [640, 480]) %>
        <% end %>
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p class="title is-6">
            <%= truncate presentation.name, length: 25 %>
          </p>
          <p class="subtitle is-7 is-muted is-family-monospace">
            <%= distance_of_time_in_words_to_now presentation.created_at %>
          </p>
        </div>

        <div class="media-right">
          <div class="dropdown is-hoverable is-right is-up">
            <div class="dropdown-trigger">
              <button class="button is-small is-white" aria-haspopup="true">
                <span class="icon is-small has-text-grey-lighter">
                  <i class="fas fa-ellipsis-v"></i>
                </span>
              </button>
            </div>

            <div class="dropdown-menu">
              <div class="dropdown-content">
                <%= link_to t('.preview'),
                  dashboard_preview_url(presentation),
                  class: 'dropdown-item',
                  target: '_blank' %>

                <%= link_to t('.edit'),
                  edit_dashboard_presentation_url(presentation),
                  class: 'dropdown-item' %>

                <%= link_to t('.remove'),
                  dashboard_presentation_url(presentation),
                  class: 'dropdown-item has-text-danger',
                  method: :delete,
                  data: { confirm: t('.confirm') } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/presentations/_toolbar.html.erb
<toolbar inline-template>
  <div class="level toolbar">
    <div class="level-left">
      <div class="level-item">
        <nav class="breadcrumb is-small" aria-label="breadcrumbs">
          <ul>
            <li>
              <%= link_to 'Presentations', dashboard_presentations_path %>
            </li>
            <li class="is-active">
              <a href="#"><%= presentation.name %></a>
            </li>
          </ul>
        </nav>
      </div>
    </div>

    <div class="level-right">
      <div class="level-item">
        <div class="field has-addons">
          <p class="control">
            <button class="button is-small is-rounded">
              <span class="icon is-small">
                <i class="fas fa-microphone"></i>
              </span>
              <span>Record audio</span>
            </button>
          </p>

          <p class="control">
            <button class="button is-small is-rounded">
              <span class="icon is-small">
                <i class="far fa-image"></i>
              </span>
              <span>Change background</span>
            </button>
          </p>

          <p class="control">
            <button class="button is-small is-rounded">
              <span class="icon is-small">
                <i class="fas fa-bolt"></i>
              </span>
              <span>Interactivity</span>
            </button>
          </p>

          <p class="control">
            <button
              id="presentation-options"
              class="button is-small is-rounded"
              @click.prevent="showOptions"
            >
              <span class="icon is-small">
                <i class="fas fa-cog"></i>
              </span>
            </button>
          </p>
        </div>
      </div>
    </div>

    <%= form_with model: [:dashboard, presentation], id: 'presentation-form' do |f| %>
      <quickview
        ref="options"
        title="Presentation"
      >
          <%= render 'form', f: f %>

          <template #actions>
            <%= f.submit class: 'button is-info is-rounded is-small' %>
          </template>
        </quickview>
      <% end %>
  </div>
</toolbar>

app/views/dashboard/presentations/edit.html.erb
<presentation-editor inline-template
  :presentation="<%= @presentation.as_json(only: %i[id name description]).to_json %>"
  :slides="<%= @slides.to_json %>"
  :urls="<%= Hash[presentations: dashboard_presentations_url].to_json %>"
  cover="<%= url_for(@presentation.cover&.variant(resize_to_fit: [870, 581])) %>"
>
  <div class="hero is-fullheight-with-navbar">
    <div class="hero-head">
      <div class="container">
        <%= render 'toolbar', presentation: @presentation %>
      </div>
    </div>

    <div class="hero-body preview">
      <div class="container">
        <div class="column is-8 is-offset-2">
          <figure class="image is-3by2">
            <img :src="currentSlide" alt="slide">
          </figure>
        </div>
      </div>
    </div>

    <div class="hero-foot timeline">
      <Timeline
        :slides="slides"
        :selected="selectedSlide"
        @selected="selectSlide"
      />
    </div>
  </div>
</presentation-editor>

app/views/dashboard/presentations/index.html.erb
<div class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Presentations
      </h1>
      <h2 class="subtitle is-4 is-muted">
        Preview, create and edit your amazing presentations
      </h2>
    </div>
  </div>
</div>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <div class="column is-3">
        <div class="card">
          <div class="card-image">
            <%= link_to new_dashboard_presentation_url, class: '' do %>
              <figure class="image is-4by3">
                <%= image_tag 'new-presentation-cover.png' %>
              </figure>
            <% end %>
          </div>
          <div class="card-content has-text-centered">
            <%= link_to new_dashboard_presentation_url, class: 'button is-info is-small is-fullwidth' do %>
              <%= t '.new' %>
            <% end -%>
          </div>
        </div>
      </div>

      <%= render @presentations, as: :presentation %>
    </div>

    <div class="column is-4 is-offset-4">
      <%== pagy_bulma_nav(@pagy) if @pagy.next %>
    </div>
  </div>
</section>

app/views/dashboard/presentations/new.html.erb
<div class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
      <%= form_with model: [:dashboard, @presentation], id: 'presentation' do |f| %>
        <div class="columns">
          <div class="column is-4 is-offset-4">
            <div class="field">
              <%= f.label :name, class: 'label' %>
              <div class="control">
                <%= f.text_field :name, class: 'input' %>
              </div>
            </div>

            <div class="field">
              <%= f.label :description, class: 'label' %>
              <div class="control">
                <div class="content">
                  <%= f.rich_text_area :description %>
                </div>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= f.file_field :source_file %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= f.submit t('.save'), class: 'button is-info is-fullwidth is-rounded' %>
              </div>
            </div>
          </div>
        </div>
      <% end -%>
    </div>
  </div>
</div>

app/views/dashboard/previews/show.html.erb
<h1><%= @presentation.name %></h1>

<% @presentation.slides.each do |slide| %>
  <p><%= image_tag slide.background_image.variant(resize_to_limit: [350, 350]) %></p>
<% end -%>

app/views/landing/_navigation.html.erb
<% content_for :navigation_end do %>
  <div class="navbar-item">
    <div class="buttons">
      <% if current_user %>
        <%= link_to t('.go_app'), dashboard_root_url, class: 'button is-text' %>
      <% else %>
        <%= link_to t('.login'), new_user_session_url, class: 'button is-text' %>
        <%= link_to t('.sign_up'), new_user_url, class: 'button is-info' %>
      <% end -%>
    </div>
  </div>
<% end %>

<%= render 'shared/navigation' %>

app/views/landing/index.html.erb
<div class="hero is-info is-medium">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Im<em>pressy</em> your audience
      </h1>
      <h2 class="subtitle">
        Turn <em>boring</em> PDF presentations into something <strong>better</strong>
      </h2>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Pressy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>

  <body>
    <div data-vue>
      <%= render 'navigation' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Pressy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'landing', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'landing', 'data-turbolinks-track': 'reload' %>

    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>

  <body>
    <%= render 'navigation' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notifications.any? %>
  <div class="notifications">
    <div class="container">
      <% notifications.each do |notification| %>
        <div class="notification <%= notification.css_class %>">
          <button class="delete"></button>
          <%= notification.message %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar is-transparent has-shadow" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to root_url, class: 'navbar-item' do %>
        <strong>pressy</strong>
      <% end %>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div class="navbar-menu">
      <div class="navbar-start">
        <%= content_for :navigation_start %>
      </div>

      <div class="navbar-end">
        <%= content_for :navigation_end %>
      </div>
    </div>
  </div>
</nav>

app/views/user_sessions/new.html.erb
<div class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="column is-4 is-offset-4">
        <%= form_with model: @user_session, id: 'user-session' do |f| %>
          <% if notifications.any? %>
            <% notifications.each do |notification| %>
              <div class="notification <%= notification.css_class %>">
                <%= notification.message %>
              </div>
            <% end %>
          <% end %>

          <div class="field">
            <%= f.label :email, class: 'label' %>
            <div class="control">
              <%= f.text_field :email, class: 'input' %>
            </div>
          </div>

          <div class="field">
            <%= f.label :password, class: 'label' %>
            <div class="control">
              <%= f.password_field :password, class: 'input' %>
            </div>
          </div>

          <div class="control">
            <%= f.submit t('.login'), class: 'button is-info is-fullwidth is-rounded' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="column is-4 is-offset-4">
        <%= form_with model: @user, id: 'user' do |f| %>
          <% if notifications.any? %>
            <% notifications.each do |notification| %>
              <div class="notification <%= notification.css_class %>">
                <%= notification.message %>
              </div>
            <% end %>
          <% end %>

          <div class="field">
            <%= f.label :email, class: 'label' %>
            <div class="control">
              <%= f.text_field :email, class: 'input' %>
            </div>
          </div>

          <div class="field">
            <%= f.label :password, class: 'label' %>
            <div class="control">
              <%= f.password_field :password, class: 'input' %>
            </div>
          </div>

          <div class="field">
            <%= f.label :password_confirmation, class: 'label' %>
            <div class="control">
              <%= f.password_field :password_confirmation, class: 'input' %>
            </div>
          </div>

          <div class="control">
            <%= f.submit t('.sign_up'), class: 'button is-info is-fullwidth is-rounded' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>